<a href="https://colab.research.google.com/github/MrckHckr/iss-digital-twin/blob/main/notebooks/04_Energy_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from scipy.optimize import minimize

import plotly.express as px
import plotly.graph_objects as go

In [2]:
modules = pd.DataFrame({
    "module":[
        "Node1",
        "Node2",
        "Harmony",
        "Columbus",
        "Kibo",
        "Cupola"
    ],

    "power_usage":[
        120,
        110,
        140,
        150,
        130,
        90
    ]
})

modules

     module  power_usage
0     Node1          120
1     Node2          110
2   Harmony          140
3  Columbus          150
4      Kibo          130
5    Cupola           90

In [3]:
current_consumption = modules["power_usage"].sum()

print(
    f"Current Consumption: {current_consumption} kW"
)

Current Consumption: 740 kW

In [4]:
minimum_power = np.array([
    100,
    90,
    120,
    130,
    110,
    80
])

In [5]:
def objective(power):

    return np.sum(power)

In [6]:
bounds = []

for min_power,current_power in zip(
    minimum_power,
    modules["power_usage"]
):

    bounds.append(
        (
            min_power,
            current_power
        )
    )

In [7]:
result = minimize(
    objective,
    x0=modules["power_usage"],
    bounds=bounds
)

In [8]:
optimized_power = result.x

modules["optimized_power"] = optimized_power

modules

     module  power_usage  optimized_power
0     Node1          120            100.0
1     Node2          110             90.0
2   Harmony          140            120.0
3  Columbus          150            130.0
4      Kibo          130            110.0
5    Cupola           90             80.0

In [9]:
optimized_consumption = optimized_power.sum()

savings = (
    current_consumption
    -
    optimized_consumption
)

print(
    f"Current: {current_consumption:.1f} kW"
)

print(
    f"Optimized: {optimized_consumption:.1f} kW"
)

print(
    f"Savings: {savings:.1f} kW"
)

Current: 740.0 kW
Optimized: 630.0 kW
Savings: 110.0 kW

In [10]:
fig = go.Figure()

fig.add_bar(
    name="Current",
    x=modules["module"],
    y=modules["power_usage"]
)

fig.add_bar(
    name="Optimized",
    x=modules["module"],
    y=modules["optimized_power"]
)

fig.update_layout(
    title="ISS Energy Optimization",
    barmode="group"
)

fig.show()

In [11]:
kpi = pd.DataFrame({
    "Metric":[
        "Current Consumption",
        "Optimized Consumption",
        "Energy Savings"
    ],

    "Value":[
        current_consumption,
        optimized_consumption,
        savings
    ]
})

kpi

                  Metric  Value
0    Current Consumption  740.0
1  Optimized Consumption  630.0
2         Energy Savings  110.0

In [12]:
modules["priority"] = [
    5,
    4,
    5,
    3,
    3,
    2
]