<a href="https://colab.research.google.com/github/MrckHckr/iss-digital-twin/blob/main/notebooks/07_ISS_3D_Visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import plotly.graph_objects as go

In [2]:
iss_modules = pd.DataFrame({

    "module":[
        "Node1",
        "Node2",
        "Harmony",
        "Columbus",
        "Kibo",
        "Cupola"
    ],

    "x":[
        0,
        2,
        1,
        -1,
        1,
        1
    ],

    "y":[
        0,
        0,
        1,
        1,
        -1,
        -2
    ],

    "z":[
        0,
        0,
        0,
        0,
        0,
        0
    ],

    "health":[
        99,
        97,
        95,
        92,
        96,
        100
    ]
})

iss_modules

     module  x  y  z  health
0     Node1  0  0  0      99
1     Node2  2  0  0      97
2   Harmony  1  1  0      95
3  Columbus -1  1  0      92
4      Kibo  1 -1  0      96
5    Cupola  1 -2  0     100

In [3]:
fig = go.Figure()

fig.add_trace(

    go.Scatter3d(

        x=iss_modules["x"],
        y=iss_modules["y"],
        z=iss_modules["z"],

        mode="markers+text",

        text=iss_modules["module"],

        marker=dict(

            size=15,

            color=iss_modules["health"],

            colorscale="Viridis",

            colorbar=dict(
                title="Health"
            )

        )
    )
)

fig.update_layout(

    title="ISS Digital Twin 3D",

    scene=dict(

        xaxis_title="X",

        yaxis_title="Y",

        zaxis_title="Z"

    )

)

fig.show()

In [4]:
connections = [

    ("Node1","Harmony"),

    ("Harmony","Node2"),

    ("Harmony","Columbus"),

    ("Harmony","Kibo"),

    ("Kibo","Cupola")

]

In [5]:
for start,end in connections:

    p1 = iss_modules[
        iss_modules["module"] == start
    ].iloc[0]

    p2 = iss_modules[
        iss_modules["module"] == end
    ].iloc[0]

    fig.add_trace(

        go.Scatter3d(

            x=[p1["x"],p2["x"]],
            y=[p1["y"],p2["y"]],
            z=[p1["z"],p2["z"]],

            mode="lines",

            showlegend=False

        )
    )

fig.show()

In [6]:
iss_modules["hover"] = (

    "Module: "
    + iss_modules["module"]

    + "<br>Health: "
    + iss_modules["health"].astype(str)
    + "%"
)

In [7]:
go.Scatter3d(

    x=iss_modules["x"],
    y=iss_modules["y"],
    z=iss_modules["z"],

    mode="markers+text",

    text=iss_modules["module"],

    hovertext=iss_modules["hover"],

    hoverinfo="text",

    marker=dict(
        size=15,
        color=iss_modules["health"],
        colorscale="Viridis"
    )

)

Scatter3d({
    'hoverinfo': 'text',
    'hovertext': array(['Module: Node1<br>Health: 99%', 'Module: Node2<br>Health: 97%',
                        'Module: Harmony<br>Health: 95%', 'Module: Columbus<br>Health: 92%',
                        'Module: Kibo<br>Health: 96%', 'Module: Cupola<br>Health: 100%'],
                       dtype=object),
    'marker': {'color': array([ 99,  97,  95,  92,  96, 100]),
               'colorscale': [[0.0, '#440154'], [0.1111111111111111, '#482878'],
                              [0.2222222222222222, '#3e4989'], [0.3333333333333333,
                              '#31688e'], [0.4444444444444444, '#26828e'],
                              [0.5555555555555556, '#1f9e89'], [0.6666666666666666,
                              '#35b779'], [0.7777777777777778, '#6ece58'],
                              [0.8888888888888888, '#b5de2b'], [1.0, '#fde725']],
               'size': 15},
    'mode': 'markers+text',
    'text': array(['Node1', 'Node2', 'Harmony', 'Columbus', 'Kibo', 'Cupola'], dtype=object),
    'x': array([ 0,  2,  1, -1,  1,  1]),
    'y': array([ 0,  0,  1,  1, -1, -2]),
    'z': array([0, 0, 0, 0, 0, 0])
})

In [8]:
def status_color(health):

    if health > 95:
        return "green"

    elif health > 90:
        return "yellow"

    else:
        return "red"

In [9]:
iss_modules["status"] = (
    iss_modules["health"]
    .apply(status_color)
)

iss_modules

     module  x  y  z  health                            hover  status
0     Node1  0  0  0      99     Module: Node1<br>Health: 99%   green
1     Node2  2  0  0      97     Module: Node2<br>Health: 97%   green
2   Harmony  1  1  0      95   Module: Harmony<br>Health: 95%  yellow
3  Columbus -1  1  0      92  Module: Columbus<br>Health: 92%  yellow
4      Kibo  1 -1  0      96      Module: Kibo<br>Health: 96%   green
5    Cupola  1 -2  0     100   Module: Cupola<br>Health: 100%   green

In [10]:
iss_modules.to_csv(
    "iss_modules.csv",
    index=False
)